### ISSUE TITLE
with xstate (statecharts)

### ISSUE THREAD

**Issue by roth1002** [dai-shi/lets-compare-global-state-with-react-hooks#1]
How about also compare with xstate ?

https://xstate.js.org/docs/packages/xstate-react/

**Comment by dai-shi** [comment]
Hi, thanks for the suggestion.

I'm not very familiar with xstate-react. xstate is an interesting library.
But, how can it be used for avoiding prop drilling?
Looked at: https://xstate.js.org/docs/packages/xstate-react/
Can `useService` be used with `useContext`?
`useActor` seems to have a subscription model. Do you know any example?

**Comment by roth1002** [comment]
It use context in machine self
https://xstate.js.org/docs/guides/context.html#initial-context
and I found the example from xstate issue discussion here (about nested component drill context)

https://github.com/davidkpiano/xstate/issues/221#issuecomment-455322649

All of feature hooks in xstate almost implement with useEffect and useState

I try to find more example later :)

**Comment by dai-shi** [comment]
> All of feature hooks in xstate almost implement with useEffect and useState

Yeah, so I assume it's mainly for local states. Just like, useState/useReducer.
I don't yet know how to use useActor.

> I try to find more example later :)

Look forward to it :)

**Comment by roth1002** [comment]
The community zoom here about context

https://spectrum.chat/statecharts/general/when-to-use-context~ed09b083-ad19-41b2-a917-bd0092742e58

**Comment by dai-shi** [comment]
I guess it's the discussion about xstate context, not React context.
It feels to me like xstate-react is a useState/useReducer level solution, and not for "global state" which _almost_ means "avoid prop drilling".

**Comment by dai-shi** [comment]
https://twitter.com/dai_shi/status/1213811280433143810
I played a little with useMachine.
If I understand it correctly, it's something like to replace useReducer.
It doesn't focus on avoiding prop drilling.
At this point, I wouldn't add it to the list, at least until somebody help us understand the usage for global state.
For now, I close this issue. Thanks for your attention.
