### ISSUE TITLE
react-easy-state not mentioned in the comparison?

### ISSUE THREAD

**Issue by kawpii** [dai-shi/lets-compare-global-state-with-react-hooks#3]
[react-easy-state](https://github.com/RisingStack/react-easy-state) is not mentioned in the comparison, please consider adding it.

**Comment by dai-shi** [comment]
Does it have Hooks API?
Just checked the README. It doesn't seem to have hooks.
Thanks for tipping in anyway!

**Comment by kawpii** [comment]
> Does it have Hooks API?

No.

But comparison would be nice either in this repo or your [react-tracked](https://github.com/dai-shi/react-tracked) repo.

**Comment by dai-shi** [comment]
Let me try adding one as an exception. I will fill it as far as I can understand from the README.

Well, I need to read the source code to fill the items.

**Comment by dai-shi** [comment]
Done! I wasn't sure about CM compatibility.
